name: Vera
options:
  bundleIdPrefix: com.vera
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  minimumXcodeGenVersion: "2.38"

targets:
  Vera:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - Vera
    settings:
      base:
        INFOPLIST_FILE: Vera/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.vera.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        TARGETED_DEVICE_FAMILY: "1"
        SWIFT_VERSION: "5.9"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: Vera/Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleDisplayName: Vera
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSRequiresIPhoneOS: true
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        NSMicrophoneUsageDescription: "Vera needs your microphone to hear you"
        NSContactsUsageDescription: "Vera needs contacts to call people on your behalf"
        NSLocalNetworkUsageDescription: "Vera connects to the bridge server on your local network"
        NSBonjourServices:
          - _http._tcp
        NSAppTransportSecurity:
          NSAllowsLocalNetworking: true
